version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: schoolmanage_postgres
    restart: always
    environment:
      POSTGRES_DB: school_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5005:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - school-net

  app:
    build: .
    container_name: schoolmanage_app
    restart: always
    ports:
      - "3500:3500"
    environment:
      DATABASE_URL: postgresql://postgres:123456789@postgres:5432/school_management
      NODE_ENV: development
    depends_on:
      - postgres
    networks:
      - school-net
    command: sh -c "npx prisma generate && npx prisma migrate deploy && node dist/index.js"

volumes:
  postgres_data:

networks:
  school-net:
    driver: bridge
